travis:
  secure:
    BINSTAR_TOKEN: AM9VJYNT2JljQtkogHCey7ZxdEzGBkk4zi/OkXfxWcSe9oW3fcwcA1jlNuo+tMAbKTndCAPr2dFkn29cjvgxyg5z72QfmbUs9mlWCHdafOs/QwREJGVZI5E4gcmC5/r+KL69inicoXb8ptEDB4UZWd8mrxEOo1DX1GcZJEjUD3uOoCfTVdhRPwifyrnBpnA6N9gkrvg3CwN1AEpQmwKeXcAoLgntucPC7XmLm8TdysvOrv/gfle6nY0wObENwQqZNS6Ms/CWyMlYn0KpIe3EWo5bqUbZ0joWMf01imav6A4PHRQcEykLaKgPXkQshez6UPgrSSZxnrcMfc5Qdb7zaeG9lhrSG4XnmLc8FWnd2ufpsLfrow+pyaM7vGQVy0/yV7PHeMDxxDlHpKzSd6TLly7/lmtCqAdR3NgLNhJ1Ffck4PvJnRUapv/CxYJPDT1/vhF5nye36LxSf9aHjeAgcKFBJ7r3ODySuBJ0kvd27gG56WTwOQKU2UIQnhpS7k80teRzWtSyotGqHfcvb7Ui0OOj2miEFQ4lQR9zn36ps9AsySqNYCvTuscPP0PF8fxGMfoEwWQmMARpBnk1cKtUNQ/XQExBOcB1yIM+fcW20ptxcnD/+R/6+y3upUhnuwaCs/5xSik7SfNfDWt9vRLc/w/mi7VU7fL3tNJd3edd9AQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
